// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQkfoANAOYfCOe_z9D4E6ygGRrYtH00Y',
    appId: '1:677099612260:web:e5ca8375df3feaa888d771',
    messagingSenderId: '677099612260',
    projectId: 'evdebilgi-8fa2d',
    authDomain: 'evdebilgi-8fa2d.firebaseapp.com',
    storageBucket: 'evdebilgi-8fa2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzcE88AefZj6LoJNGcvxMkzq6vFgE3Ik',
    appId: '1:677099612260:android:c41eae2a82b8c25c88d771',
    messagingSenderId: '677099612260',
    projectId: 'evdebilgi-8fa2d',
    storageBucket: 'evdebilgi-8fa2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQx-oO9U4S0baTXge-y4Q2-GHPtGGS5AI',
    appId: '1:677099612260:ios:56d3369ce15730c188d771',
    messagingSenderId: '677099612260',
    projectId: 'evdebilgi-8fa2d',
    storageBucket: 'evdebilgi-8fa2d.appspot.com',
    iosBundleId: 'com.example.evdeBilgi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQx-oO9U4S0baTXge-y4Q2-GHPtGGS5AI',
    appId: '1:677099612260:ios:56d3369ce15730c188d771',
    messagingSenderId: '677099612260',
    projectId: 'evdebilgi-8fa2d',
    storageBucket: 'evdebilgi-8fa2d.appspot.com',
    iosBundleId: 'com.example.evdeBilgi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChQkfoANAOYfCOe_z9D4E6ygGRrYtH00Y',
    appId: '1:677099612260:web:2c4670eb3cd085fc88d771',
    messagingSenderId: '677099612260',
    projectId: 'evdebilgi-8fa2d',
    authDomain: 'evdebilgi-8fa2d.firebaseapp.com',
    storageBucket: 'evdebilgi-8fa2d.appspot.com',
  );
}
